### ISSUE TITLE
【翻译】DOC-03-14 Servers

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#65]
开始翻译

**Comment by UtilCore** [comment]
Document Urls：https://docs.asp.net/en/latest/fundamentals/servers.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/servers.rst

**Comment by YaoaY** [comment]
Host ： 承载
self-hosted：自承载

1. 
>ASP.NET Core 完全从托管应用程序的Web服务器环境脱离。 ASP.NET Core支持宿主在IIS、IIS Express、使用Kestrel的自托管脚本或者WebListener HTTP服务器。

建议：

> ASP.NET Core 已完全从承载应用程序的 Web 服务器环境中分离。ASP.NET Core 可以承载于 IIS 和 IIS Express ，以及使用 Kestrel 和 WebListener HTTP Server 的自承载环境中。


2.
>ASP.NET Core 的设计目标是从底层HTTP服务器分离出Web应用程序。传统的方式下，ASP.NET应用程序只能托管在基于window的IIS服务器上。ASP.NET Core应用程序在window上运行推荐使用IIS作为反向代理服务器。ASP.NET Core附带两个不同的HTTP服务器，在IIS中的HttpPlatformHandler模块管理和HTTP服务器托管进程外的代理请求

建议：

>ASP.NET Core 旨在将 Web 应用程序从底层 HTTP 服务器分离出来。过去，ASP.NET 应用一直只在 Windows 中承载于 IIS 上。在 Windows 上运行 ASP.NET Core 应用程序的推荐方法是将 IIS 作为一个反向代理服务器来使用。IIS 中的 HttpPlatformHandler 模块管理并分发请求给一个进程外的HTTP 服务器。ASP.NET Core附带两个不同的HTTP服务器：

3
> Windows-专用

建议改为：

> 仅 Windows

**Comment by YaoaY** [comment]
4.
`
ASP.NET Core does not directly listen for requests, but instead relies on the HTTP server implementation to surface the request to the application as a set of feature interfaces composed into an HttpContext.
`

> ASP.NET Core 不直接监听请求，而是依赖于 HTTP 服务器实现的一组集成在 HttpContext中的Feature接口来将请求暴露给应用程序 。

建议：

> ASP.NET Core 不直接监听请求，而是依靠 HTTP 服务器的实现将请求作为组成 HttpContext 的一组功能接口暴露给应用程序。

5.
`
You can configure your application to be hosted by any or all of these servers by specifying commands in your project.json file.
`

> 你可以通过指定配置*project.json*文件中的命令来配置让你的应用程序托管到一个或者多个应用服务器。

> 你可以通过在 project.json 文件中指定命令来配置你的应用程序承载于任何一个或全部的服务器。

6.
`
 You can even specify an application entry point for your application, and run it as an executable (using dotnet run) rather than hosting it in a separate process.
`

> 你甚至可以为应用程序指定的应用程序入口点，作为一个可执行文件运行（使用``dotnet run``），而不是托管到独立的进程。

> 你甚至可以为应用程序指定程序入口点，作为一个可执行文件运行（使用 ``dotnet run``），而不是承载到不同的进程。
